### PR TITLE
Trying to get this to work on my PC

### PR DESCRIPTION
**Pull request by kjhsdgf**
Made some progress; added a project property sheet, and moved things around for compatibility. But, it's still unfinished. I think by the end of things, I'll need to use macros to make the filepath before /mkl irrelevant.

### CODE REVIEW

**Comment by patelami3431** [comment]
This code works on mine. What exactly is the error given by the compiler?

**Comment by kjhsdgf** [comment]
So, I did end up getting it to build after some fuss. Here's what I did:

When immediately opening your branch, I get these errors (you may get similar ones if you try to open my branch)
filepath not working oct 17
After some editing (not macros, but by dropping the files into Network>Network and following the prompts to reload the solution), I can get the files to open. 

Then, I tried to build, here's the output:
bunked up linkages oct 17
I tried a couple of things:
* disabling mkl performance libraries in View>Other Windows>Property Manager>Debug | x64 > Microsoft.Cpp.x64.user (seemed to work, can also use Project>Properties>Intel Performance Libraries)
* linking everything in and setting the dependencies up (a little progress there, but more build errors than it's worth atm)

Once I copied the dlib (and mkl, hopefully you might consider using it in the future, as it may improve calculation speeds during training) folders into the repo directory, the libraries were included and the compiler built the solution without errors. On a side note: also deleted stuff that wasn't used in VS 2017, like the Documents Folder, Network Class folder, etc, which can be found and manipulated in `master`, but do whatever you want with that.

**Comment by kjhsdgf** [comment]
An important upshot is that, in order to run our code on another PC, we have to adjust a bunch of settings just to get the compiler to build -- and I don't believe this is an artifact of using GitHub, since it's effectively a fancy copy/paste. It may be worth our interest to create Project Property sheets or *something* to make sure directory settings and dependencies get transferred with the source code.
Essentially, I think what I'm talking about is [making a dynamic link library (dll)](https://docs.microsoft.com/en-us/cpp/build/walkthrough-creating-and-using-a-dynamic-link-library-cpp).

**Comment by kjhsdgf** [comment]
Here's a [link to a branch with the changes](https://github.com/kjhsdgf/Collin-Neural-Network/tree/Sandbox-patelami3432-augmented).

**Pull request closed without merging**
