### PR TITLE
Added costPrime() and distribution()

### PR DESCRIPTION
**Pull request by kjhsdgf**
All things considered, there's probably a better way around using distribution this way.
Earlier, we had thrown out the idea to have the user write randomizeMatrix(), with whatever distribution they desire. Since randomizeMatrix()'s parameters and return type are far more regular -- at least, I imagine -- we can use the function far more extensively, even if we end up using function pointers. So, that may have been the better option.

### CODE REVIEW

**Comment by patelami3431** [comment]
The thing is because distribution() is outside the class, it can be called directly in the randomizeMatrix(). I think using pointer to the function and passing it as a parameter would make no sense.

**Comment by kjhsdgf** [comment]
What I was suggesting is that we have the user write `randomizeMatrix()`, and provide accessor functions so that they may accomplish whatever convoluted `distribution()`s their little hearts desire. Being able to call `randomizeMatrix()` -- or `distribution()` for that matter -- from a file by its name makes enough sense. Besides, changing from regular calls to function pointers takes all of 2 minutes.

To the point of my suggestion:
Whereas `distribution()` can be wildly varied in parametrization, `randomizeMatrix()` will typically take a `matrix<double>` and return a `matrix<double>` (on a side note, we may want to upgrade that to long double, because the numbers that Nielsen's random distributions were putting out were *really* tiny). That regularity can save us time. Users may have all sorts of means to create random distributions, even ways that aren't accounted for in how `randomizeMatrix()` is written -- for this case, `randomizeMatrix()` uses `distribution()` as though it takes no arguments, but that may not always be the case. Supposing we grant users accessor (or "getter") functions, then they'll have the flexibility to write nuanced functions (yes, distribution, but also others) without being able to fuss with the data and break the code.

**Comment by patelami3431** [comment]
Oh, okay! I was thinking we are the ones defining randomizeMatrix() and distribution(). So, we are prompting user to choose what kind of distribution() to be used to initialize the matrices. But if the user is allowed to enter the name of the file in which the distribution(), we need to make it accessible in the header. But now I see, what you meant by using pointer to the function.
Usually, the pointers to any function are used as parameters of the functions outside the class, so that without declaring any object of that class, we can access the public functions of a class. But I agree we should do this, just that I am concerned about reading a function from the file and defining each term of the function.

**Comment by kjhsdgf** [comment]
Potter suggested we put weight initialization into the hands of the user, iirc. I'm having trouble understanding what you meant by,

> But if the user is allowed to enter the name of the file in which the distribution(), we need to make it accessible in the header.

It would still be viable to `#include "Auxillary_Functions.cpp"` and just use the function name. I'm thinking Slater may have insight into why function pointers are an improvement over just including the file. But, it seems like you mentioned a good reason, though I had its usage backwards: the pointers should be to the functions inside of the class, to be referenced outside! I'm unsure of how the addresses get assigned without instantiating the class, however. 

So, I'm going to go ahead and write `randomizeMatrix()` and include it in this branch. Should we opt to use function pointers or functors or a standard function calls, (as far as I know) we can quickly update the functions no matter the case.

Furthermore, please consider adding some accessor functions to return data from within the network, i.e.
`int * const getLayerSizes()` to return a const pointer to the array of layer sizes. This will give the user more flexibility with which to add to the class without changing anything fundamental.

**Comment by patelami3431** [comment]
Yeah, I would say let's use the functors for now. We can change it later if needed!

**Pull request closed without merging**
